### ISSUE TITLE
持ち上げてる間はtransform.rotate、離した瞬間にaddTorqueを試してみる

### ISSUE THREAD

**Issue by keisato3310** [keisato3310/unity-dice#1]

**Comment by awl-kei-sato** [comment]
https://github.com/keisato3310/unity-dice/commit/da6c80070af71d6d4644c4476d237ab5d922c44f にて対応完了

**Comment by keisato3310** [comment]
https://github.com/keisato3310/unity-dice/commit/da6c80070af71d6d4644c4476d237ab5d922c44f にて対応完了
